### ISSUE TITLE
データを絞り込めるようにする

### ISSUE THREAD

**Issue by ltoppyl** [ltoppyl/mahjong-score-manage#106]
## ✨ 概要

- 以下の条件でデータを絞り込んで表示できるようにする
  - ゲームタイプ (4麻 or 3麻 or どちらも)
  - 日付 

## 🔥 ゴール

- データを絞り込んで表示することができる

## ✅ タスク

- [x] [BE] DB のリアーキテクト (collection 周りの修正)
- [x] [BE] API の修正 #107
- [ ] [FE] UI の実装

**Comment by ltoppyl** [comment]
### MEMO
[BE] DB のリアーキテクト (collection 周りの修正) は必要がないという結論に至った
https://discordapp.com/channels/1098770371211186256/1099149117969682554/1115464870922567721
